name = "insertaquarter"
pages_build_output_dir = "."

compatibility_date = "2025-01-01"

[vars]
CORS_ORIGIN = "*"

[[d1_databases]]
binding = "DB"
database_name = "iaq"
database_id = "926ed94b-f3d2-4bc1-a5a8-88ecb1e6c0d1"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "retroarcade-assets"
